### PR TITLE
Tried to replicate Nick's layout  lol

### PR DESCRIPTION
**Pull request by yashika51**
It's not at all pretty but it's an office view at least 😭

### CODE REVIEW

**Comment by akainth015** [comment]
Whoa this looks awesome! Let's make it use the data from Firebase!

**Comment by yashika51** [comment]
I have just made the changes but I am not sure if this would work coz the main page is not redirecting me to officeview now and running app with master gives me error(pulled all the changes). So I cannot see how it looks :(
I might be missing smth though.

**Comment by yashika51** [comment]
Not sure if you can hear me on discord, so I made a mistake I accidentally pushed to master instead to this branch so I am figuring how to revert that back

**Comment by akainth015** [comment]
I think you reverted the wrong commit. `master` was fine, I will fix it

**Comment by yashika51** [comment]
Please and thank you!

**Comment by yashika51** [comment]
So I didn't change the code much. I have no idea if it would work fine. Is there a way to check how the office view looks now?

**Comment by akainth015** [comment]
Let me see the latest changes

**Comment by akainth015** [comment]
Okay done you can take a look at it now

**Comment by yashika51** [comment]
Pulled the latest changes. npm run start takes me to 
image

**Comment by akainth015** [comment]
Try creating a new account instead, that should fix the issue

**Comment by yashika51** [comment]
As soon as the app opens it redirects to this page. Is this due to the code change in `OfficeView.js`

**Comment by akainth015** [comment]
No, I don't think so. Try deleting your account through the Firebase console

**Comment by yashika51** [comment]
okay

**Comment by yashika51** [comment]
It's not working :(
`Unhandled Rejection (TypeError): Cannot read property 'offices' of undefined`

**Comment by akainth015** [comment]
I just manually added the entries into the database. Can you try again?

**Comment by yashika51** [comment]
It redirects to office view and within 5 seconds it takes back to the same error ^

**Comment by akainth015** [comment]
Can you please checkout master and make a new branch with your changes, this branch and master have diverged and it will be a massive pain to merge them as they stand.

**Comment by yashika51** [comment]
That makes sense ✅

**Comment by akainth015** [comment]
Also by the way, when you run into the `offices` error, reloading seems to fix the problem

**Pull request closed without merging**
